config/routes.rb
Rails.application.routes.draw do
  resources :skirmishes, only: [:index]

  resources :songs, only: [:index]

  root 'pages#home'

  get 'podcast.rss', to: 'songs#index', defaults: { format: 'xml' }

  get 'about', to: 'pages#about'
end

app/models/podcast.rb
require 'rss/2.0'
require 'rss/itunes'

class Podcast

  def initialize(songs)
    @songs = songs

    @rss = RSS::Rss.new( "2.0" )

    @channel = RSS::Rss::Channel.new
    @channel.language = 'en'

    yield @channel

    @rss.channel = @channel
  end

  def to_rss
    @songs.each do |song|
      item = RSS::Rss::Channel::Item.new
      item.title = "#{song.title} - #{song.username}"
      item.link = song.remote_url
      item.pubDate = song.posted_date.to_time
      item.description = [song.liner_notes, song.lyrics].compact.join("\n\n")

      item.enclosure = RSS::Rss::Channel::Item::Enclosure.new(song.demo_href, 0, 'audio/mpeg')
      @channel.items << item
    end

    @rss.to_s
  end

end

app/models/skirmish.rb
class Skirmish < ActiveRecord::Base

  def url
    "http://fiftyninety.fawmers.org/#{remote_url}"
  end

end

app/models/song.rb
require 'uri'

class Song < ActiveRecord::Base

  def remote_url
    URI.join('http://fiftyninety.fawmers.org/song/', remote_id.to_s).to_s
  end

  def remote_user_url
    URI.join('http://fiftyninety.fawmers.org/', user_href).to_s
  end

end

app/models/songwriter.rb
class Songwriter

  def initialize(handle)
    @handle = handle
  end

  def songs
    Song.where(user_href: "/user/#{handle}").order('posted_date DESC')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @current_page_title = 'About'
  end

  def home
    @current_page_title = 'Home'
  end
end

app/controllers/skirmishes_controller.rb
class SkirmishesController < ApplicationController
  YEAR = 2016
  START_DATE = Date.new(YEAR, 7, 4)
  END_DATE = START_DATE + 89
  DATES_FOR_CALENDAR = START_DATE.beginning_of_week(:sunday)..END_DATE.end_of_week(:sunday)

  # GET /skirmishes
  # GET /skirmishes.ics
  def index
    @current_page_title = 'Skirmishes'
    @skirmishes = Skirmish.order('starts_at desc NULLS LAST').all

    respond_to do |format|
      format.html do
        skirmishes_by_date = @skirmishes.select(&:starts_at).
          group_by{|s| s.starts_at.to_date}

        skirmish_dates = DATES_FOR_CALENDAR.map do |d|
          {
            date: d,
            during_5090: (Date.new(2016,7,4)..Date.new(2016,10,1)).include?(d),
            skirmishes: skirmishes_by_date[d] || [],
          }
        end

        @weeks = skirmish_dates.each_slice(7)
      end

      format.ics do
        calendar = Icalendar::Calendar.new

        @skirmishes.each do |skirmish|
          if skirmish.starts_at
            calendar.event do |e|
              e.dtstart = skirmish.starts_at.strftime('%Y%m%dT%H%M%SZ')
              e.dtend = (skirmish.starts_at + 1.hour).strftime('%Y%m%dT%H%M%SZ')
              e.summary = '50/90 Skirmish'
              e.description = skirmish.url
              e.url = skirmish.url
            end
          end
        end

        calendar.publish

        render :text => calendar.to_ical
      end
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  # GET /songs
  def index
    @current_page_title = 'Songs'
    @songs = Song.order('remote_id desc').all

    respond_to do |format|
      format.html # index.html.erb
      format.xml do
        podcast = Podcast.new(@songs) do |channel|
          channel.title = 'NiftyFinety.com: All 50/90 Demos'
          channel.description = 'A podcast of all downloadable 50/90 demos, updated hourly.'
          channel.link = 'http://niftyfinety.com'

          # Author info for iTunes.  Otherwise, newest song's author is displayed.
          channel.itunes_author = 'NiftyFinety'
          channel.itunes_owner = RSS::ITunesChannelModel::ITunesOwner.new
          channel.itunes_owner.itunes_name = 'NiftyFinety'

          # Album art for iTunes
          channel.image = RSS::Rss::Channel::Image.new
          channel.image.url = URI.join(
            'http://niftyfinety.com',
            ActionController::Base.helpers.asset_url('podcast_logo.png')
          )
          channel.image.title = channel.title
          channel.image.link = channel.link
        end

        render :xml => podcast.to_rss
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link_to(title, target)
    options = (title == @current_page_title) ? {class: 'active'} : {}
    content_tag(:li, options) do
      link_to title, target
    end
  end

  ZONES = {
    'EDT' => ActiveSupport::TimeZone["Eastern Time (US & Canada)"],
    'PDT' => ActiveSupport::TimeZone["Pacific Time (US & Canada)"],
    'GMT' => ActiveSupport::TimeZone["London"],
  }

  def skirmish_link(skirmish)
    t = skirmish.starts_at

    zoned = ZONES.map do |name, tz|
      h = tz.utc_to_local(t).hour
      "#{((h - 1) % 12) + 1}#{ (h > 11 && h < 24) ? 'PM' : 'AM'}&nbsp;#{name}"
    end.join(' / ').html_safe

    link_to zoned, skirmish.url
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>NiftyFinety</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="../assets/js/html5shiv.js"></script>
  <![endif]-->

  <!-- Fav and touch icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  <link rel="shortcut icon" href="../assets/ico/favicon.png">
</head>

<body>
  <div class="container-narrow">

    <div class="masthead">
      <ul class="nav nav-pills pull-right">
        <%= nav_link_to 'Home', root_url %>
        <%= nav_link_to 'Songs', songs_url %>
        <%= nav_link_to 'Skirmishes', skirmishes_url %>
      </ul>
      <h3 class="muted">NiftyFinety</h3>
    </div>

    <hr>

    <%= yield %>

    <hr>

    <div class="footer">
      <p>
        Website by <%= link_to 'Matt Gillooly', 'http://fiftyninety.fawmers.org/user/mattgillooly' %>.
        All songs copyright their respective owners.
      </p>

      <p>
        Follow us <%= link_to 'on Twitter', 'http://twitter.com/NiftyFinety' %>.
        Get <%= link_to 'updates via email', 'http://tinyletter.com/NiftyFinety' %>.
      </p>
    </div>

  </div> <!-- /container -->

</body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65828634-1', 'auto');
  ga('send', 'pageview');
</script>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Enjoy 50/90 demos as a podcast</h1>
  <p class="lead">A podcast (and more?) to enhance your 50/90 experience</p>
  <a class="btn btn-large btn-success" href="itpc://feeds.feedburner.com/NiftyfinetycomAll50/90Demos">Subscribe in iTunes</a>
  <a class="btn btn-large btn-default" href="pcast://feeds.feedburner.com/NiftyfinetycomAll50/90Demos">Subscribe in Podcast app</a>

  <hr>

  <p>
    Feed URL: <%= link_to 'http://feeds.feedburner.com/NiftyfinetycomAll50/90Demos', 'http://feeds.feedburner.com/NiftyfinetycomAll50/90Demos' %>
  </p>
</div>

<hr>

<div class="row marketing">
  <div class="col-md-6">
    <h4>What is 50/90?</h4>
    <p><%= link_to '50/90', 'http://fiftyninety.fawmers.org/' %> is a summer-long songwriting challenge.</p>
    <blockquote> This is the marathon of songwriting known as the 50 Songs in 90 Days Challenge. Between July 4th and October 1st, participants attempt to write fifty songs. Songwriters will test their creative mettle by trying to create a finished song in less than 2 days every day for nearly 3 months.</blockquote>

    <h4>Why does this podcast exist?</h4>
    <p>I often listen to podcasts while driving, and I thought this would be a great way to keep caught-up on people's demos while I'm away from my computer.
    So far, it's helped me listen to a lot more great songs, and I hope it helps you too!</p>

    <h4>What's in the podcast?</h4>
    <p>Ideally, every demo posted to <%= link_to 'http://fiftyninety.fawmers.org/', 'http://fiftyninety.fawmers.org/' %> with the "Downloadable" option selected should appear as an episode in the podcast.  Note that this does currently include any that are marked NSFW.</p>
    <p>You can see the <%= link_to 'list of songs', songs_url %> to see what is currently in the podcast.</p>
  </div>

  <div class="col-md-6">
    <h4>What if something is missing?</h4>
    <ul>
    <li>When you first subscribe the the podcast, your player may hide older demos, so first make sure the missing song isn't in that hidden backlog.</li>
    <li>The podcast is only updated once per hour, so if you posted your demo recently, you may have to wait a bit for it to show up.</li>
    <li>Also, note that it only looks at new songs, so if you add a demo to a pre-existing song, then it is unlikely to be added automatically.</li>
    <li>Finally, make sure the demo is marked as Downloadable, and was added with a URL directly to the file, and not as a streaming link to Soundcloud, Youtube, etc.</li>
    </ul>
    <p>If you suspect a demo meets these criteria and is still missing, then you have probably found a bug and I would like to fix it!  Please let me know via <%= link_to 'my 50/90 contact form', 'http://fiftyninety.fawmers.org/user/mattgillooly' %>.</p>

    <h4>What else?</h4>
    <p>Please contact me via <%= link_to 'my 50/90 contact form', 'http://fiftyninety.fawmers.org/user/mattgillooly' %> if you have any questions / comments / suggestions / etc.</p>
    <p>I'll be working on improvements to this during the remainder of 50/90.
    You can <%= link_to 'sign up for the email newsletter', 'http://tinyletter.com/NiftyFinety' %> if you'd like to get infrequent updates about new features and bug fixes.</p>

  </div>
</div>

app/views/skirmishes/index.html.erb
<h1>Skirmishes</h1>

<p>
This list is updated every hour.
If something looks wrong, please let me know via <%= link_to 'my 50/90 contact form', 'http://fiftyninety.fawmers.org/user/mattgillooly' %>.</p>
</p>

<div style="margin-bottom: 40px;">
  <p>
    You can keep track of the skirmishes in your favorite calendar application.
    Either copy-and-paste the URL:
    <code><%= skirmishes_url(format: 'ics') %></code>
    or click this button:
  </p>


  <%= link_to skirmishes_url(protocol: 'webcal', format: 'ics'), class: 'btn btn-default' do %>
    <i class="glyphicon glyphicon-calendar"></i>
    Subscribe to iCalendar Feed
  <% end %>

</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Sunday</th>
      <th>Monday</th>
      <th>Tuesday</th>
      <th>Wednesday</th>
      <th>Thursday</th>
      <th>Friday</th>
      <th>Saturday</th>
    </tr>
  </thead>

  <tbody>
    <% @weeks.each do |week| %>
      <tr>
        <% week.each do |date| %>
          <%= content_tag :td, style: (date[:skirmishes].empty? ? '' : "background-color: #eef;") do %>
            <% if date[:during_5090] %>
              <p class="initialism">
                <%= date[:date].strftime('%b %e') %>
              </p>
              <% date[:skirmishes].each do |skirmish| %>
                <br />
                <%= skirmish_link skirmish %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<table class="table">
  <thead>
    <tr>
      <th>Starts at</th>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
    <% @skirmishes.each do |skirmish| %>
      <tr>
        <td><%= skirmish.starts_at %></td>
        <td><%= link_to skirmish.title, skirmish.url %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/songs/index.html.erb
<h1>All Downloadable Demos</h1>

<p>
This list is updated every hour.
If something looks wrong, please let me know via <%= link_to 'my 50/90 contact form', 'http://fiftyninety.fawmers.org/user/mattgillooly' %>.</p>
</p>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Demo</th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= link_to(song.title, song.remote_url) %></td>
        <td><%= link_to(song.username, song.remote_user_url) %></td>
        <td><%= link_to('Demo', song.demo_href) %></td>
      </tr>
    <% end %>
  </tbody>
</table>